export const FETCH_ALL_USERS_DATA = 'FETCH_ALL_USERS_DATA';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const REQUEST_NEW_USERS_REGISTRATION = 'REQUEST_NEW_USERS_REGISTRATION';
export const RECEIVE_NEW_USERS_REGISTRATION = 'RECEIVE_NEW_USERS_REGISTRATION';
export const RESET_NEW_USERS_REGISTRATION = 'RESET_NEW_USERS_REGISTRATION';

// --
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
