export const FETCH_ALL_USERS_DATA = 'FETCH_ALL_USERS_DATA';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const REQUEST_NEW_USER_REGISTRATION = 'REQUEST_NEW_USER_REGISTRATION';
export const RECEIVE_NEW_USER_REGISTRATION = 'RECEIVE_NEW_USER_REGISTRATION';
